### ISSUE TITLE
What should happen if a canceler throws

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-aff#110]
For example, with the Alt instance, if a thread succeeds, but in the process of killing the other threads, one of them throws, should the entire Alt throw? Or should we throw the error in a fresh stack and continue with a success?

**Comment by natefaubion** [comment]
Right now, if a canceler throws in an Alt, the entire Alt will throw.

**Comment by jdegoes** [comment]
I think the failure to cancel an already completed result should not affect a branch of the `Alt`.

**Comment by natefaubion** [comment]
I think that's right. I did that for `supervise` but did not go back and do it for `ParAff`. The question I have now is, should errors during cancellation _ever_ propagate? If I call `kill` on a thread, and a canceler somewhere throws, should the `kill` throw? I think that may not be desired, or even have sensible semantics because in the case of ParAff or supervise, where lots of threads may be killed as a result, it doesn't make sense to only propagate _one_ of the errors if many of them may error. I'd prefer not to swallow exceptions unless recovery is part of the semantics of the operation. Perhaps it should instead always return with a success, but the error should be thrown in a fresh stack?

**Comment by jdegoes** [comment]
>  If I call kill on a thread, and a canceler somewhere throws, should the kill throw?

I don't think so. It would be nice to have a soft guarantee that `kill` never throws an exception.

> Perhaps it should instead always return with a success, but the error should be thrown in a fresh stack?

There is an unresolved question (both here and in the Scala work I'm doing) of how to handle errors with no obvious output. Cancelers are one point (if semantics are changed as noted) but finalizers are another. Finalizers must always be run, inner to outer, even if inner finalizers fail. Now these errors disappear into a black hole.

Javascript has `window.onerror` which is one potential sink to dump these global errors into, lacking a better alternative.

**Comment by natefaubion** [comment]
> Javascript has window.onerror which is one potential sink to dump these global errors into, lacking a better alternative.

Yes that's the idea. I don't want to swallow errors, and JS runtimes at least have a global handler to observe exceptions like this. It's possible we could add our own thing as well, but I don't really want to do that unless we find it's really necessary.
