### ISSUE TITLE
Signature of runAff and makeAff

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-aff#112]
I had changed it to use `Either`, but I'm thinking it might best to retain the old signature, if only because it's one less thing to change.

**Comment by garyb** [comment]
I like the new one personally 🤷‍♂️

**Comment by mwalkerwells** [comment]
Quick question (I'm new to Purescript)... Im writing a FFI for Dropbox & the previous definition for ``makeAff`` made more sense to me:
```js
makeAff :: forall e a. ((Error -> Eff e Unit) -> (a -> Eff e Unit) -> Eff e Unit) -> Aff e a

```
https://github.com/slamdata/purescript-aff/commit/aef5f1be8655cd2b3c3e62e4d2e586697c944c29#diff-24709946a5e13e861d9d85dde96c03d1L52

**vs**

```js
makeAff ∷ ∀ eff a. ((Either Error a → Eff eff Unit) → Eff eff (Canceler eff)) → Aff eff a
```
https://github.com/slamdata/purescript-aff/blob/master/src/Control/Monad/Aff.purs#L365

When I construct a ``Promise``, the parameters are two callbacks (success & failures handlers), not a single function that handles either an error or value.

What am I missing?

**Comment by kRITZCREEK** [comment]
@mwalkerwells Where you previously had

```purescript
makeAff errorCallback successCallback
```
 you can now do:

```purescript
makeAff (case _ of
  Left error -> errorCallback error
  Right success -> successCallback success)
```

This might seem more tedious at first, but the benefit of this new API is that we can use all the helper functions for Either's we have available in PureScript:

```purescript
-- The same but shorter
makeAff (either errorCallback successCallback)

-- Only reacting to the success case
makeAff (map successCallback)

-- Only reacting to the error case
makeAff (lmap successCallback)

-- Passing the result on to a function which expects `Maybe` instead of `Either`
makeAff (maybeHandler <<< hush)
```
