### ISSUE TITLE
Rejecting/Resolving aff multiple times in makeAff

### ISSUE THREAD

**Issue by FrigoEU** [slamdata/purescript-aff#115]
Hey, 

I apologise if this is not a bug but rather a hole in my understanding, but I was very surprised to see that when I make new aff's with makeAff/makeAff', I can resolve and reject them multiple times. Is this expected behavior? It feels unintuitive to me because it's the opposite of how eg. JavaScript's promises work.

**Comment by garyb** [comment]
For the pre-v4 release it's expected, as `Aff` supported continuation behaviour.

**Comment by FrigoEU** [comment]
Great, thanks for the swift answer! Just out of curiosity, will this change in V4?

**Comment by garyb** [comment]
Yeah, in v4 the contination behaviour has been dropped, because it's confusing/surprising, as you found :smile:. It'd been intended to be deprecated for a while, but as there are other fairly major changes with v4 it seemed as good a time as any.

**Comment by FrigoEU** [comment]
Awesome, thanks for the help!
