### ISSUE TITLE
Arguments ordering for `kill` functions

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-aff#118]
* `killFiber :: Error -> Fiber eff a -> Aff eff Unit`
* `killVar :: AVar a -> Error -> Aff (avar :: AVAR | eff) Unit`

Should the error come first or second?

**Comment by jdegoes** [comment]
I believe the error should always come first, as this allows you to create constructors for different families of errors. Whereas I can't see any use for fixing the action but varying the error.

**Comment by natefaubion** [comment]
I agree, which is why I made `killFiber` what it is. But all the AVar actions have the AVar first :/. Personally I really hate AVar first, but all the Ref APIs use this order as well 😞

**Comment by natefaubion** [comment]
Closed via #119
