### ISSUE TITLE
Race in ParAff?

### ISSUE THREAD

**Issue by ford-prefect** [slamdata/purescript-aff#123]
When I run the following code, I see different behaviour from Chrome vs. Firefox:

```
  oneOf [ ParAff delay_print_and_recurse
             , ParAff delay_print_and_return
  ]
```

On Chrome, as expected, both `Aff`s above run, and after the second one is done, the first is terminated.

On Firefox, most times, only the first one runs forever. There are occasionally some other weird behaviours, but this is mostly it.

The behaviour is also the same with `master`, using `parOneOf`. Also similarly consistent on Chrome vs. Firefox on mobile. Things work as expected on Node (`pulp run`).

The full code is at:

  https://gist.github.com/ford-prefect/3a07d9df612934b81eaaf94980ec35cf

**Comment by garyb** [comment]
Which version of Aff is this in?

**Comment by ford-prefect** [comment]
I've tried with 3.1.0 and 4.0.0-rc.6 (needed a quick fixup to move to `parOneOf`)

p.s.: the compiled code is available to try on https://arunraghavan.net/temp/ps/

**Comment by garyb** [comment]
In IE/Edge it print's "ho" once and stops :scream:

**Comment by ford-prefect** [comment]
This is embarassing :( -- the problem is the usage of `document.write()`in the JS debug code. Snippet updated, as is the page on my website -- seems to work on Firefox too.

**Comment by garyb** [comment]
Browsers 🤦‍♂️ 

Thanks though, I'm very glad that's all it was! :smile:
