### ISSUE TITLE
Canceling peekVar, putVar, takeVar

### ISSUE THREAD

**Issue by felixSchl** [slamdata/purescript-aff#125]
`peekVar`, `putVar` and `takeVar` are not canceling their consumer function when the containing `Aff` computation gets cancelled. This caused severe memory leaks in an application I am building at least in versions < 4 (not tested in 4). I have no fix as it is not obvious to me as to how this cancelation should take place in the current v3 codebase. Is this an oversight or intended behaviour?

**Comment by jdegoes** [comment]
Would be good to test in 4 since 4 is a total rewrite and may fix this issue.

**Comment by felixSchl** [comment]
Are you open to the idea of maintaining v3 for a little longer? I've got a patch ready for this I am about to submit a PR for.

**Comment by felixSchl** [comment]
In case you _are_, could you create a branch "v3" (or similar) on this repo that I can use as the target of my PR?

**Comment by natefaubion** [comment]
Yes, this issue was previously noted #91 and fixed in v4.

**Comment by natefaubion** [comment]
Another option is to just write some simple v3 bindings to `purescript-avar` for the time being.

**Comment by felixSchl** [comment]
@natefaubion with (very recent) releases to nearly all libraries that I depend on, I am happy to move on to v4, so we can close this.
