### ISSUE TITLE
Could use a makeAff'?

### ISSUE THREAD

**Issue by justinwoo** [slamdata/purescript-aff#126]
It seems like a lot of times people just need a nonCanceler, so `mempty <$ thing` ends up being the body of a lot of makeAff calls. Would this make sense to have as `makeAff'` or something?

**Comment by jdegoes** [comment]
👍

**Comment by natefaubion** [comment]
I removed this on purpose, because after looking at code in the wild, I'd say it encourages people to omit a canceler when they could otherwise write one. Cancellation shouldn't be an afterthought, and I'd rather have the reminder that you should consider writing one if possible.

**Comment by garyb** [comment]
It already worked for me, I made `awaitBody` in Halogen cancellable.

By the way, we should have fixed the spelling of `Canceller` while we were doing this stuff, but oh well 😆

**Comment by natefaubion** [comment]
`Canceler` is a correct spelling according to the dictionary, but it always gets me...

But yeah, in any case, `nonCanceler` should always be explicit, as a reminder that you are potentially leaking resources.

**Comment by garyb** [comment]
Not in my dictionary, maybe it's a US thing. Although, it seems from googling it either spelling is equally acceptable more or less.

**Comment by natefaubion** [comment]
It's in my dictionary app provided by apple :P

**Comment by natefaubion** [comment]
Closing this as wontfix.
