### ISSUE TITLE
ParAff Apply instance should abort on an unhandled exception

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-aff#134]
Right now if one side of `apply` throws an exception, it will still wait until the other side completes. We should kill the other side. Since the entire tree is in an error state at that point there's no use in waiting around.

**Comment by garyb** [comment]
This is something that old Aff did wrong for a while but was eventually fixed :smile:

**Comment by jdegoes** [comment]
👍

**Comment by natefaubion** [comment]
So it's a regression? That means I can fix ASAP :)
