### ISSUE TITLE
use setImmediate in _setTimeout when millis is less than 4

### ISSUE THREAD

**Issue by michaelficarra** [slamdata/purescript-aff#21]
The HTML5 `setTimeout` function will use a value of four for any timeout value less than four (see [step 7 in Section 8.4](https://html.spec.whatwg.org/multipage/webappapis.html#timers)). `_setTimeout` should use [`setImmediate`](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) for calls with a `millis` value less than four, or at least for calls with a `millis` value of zero.

**Comment by jdegoes** [comment]
:+1:
