### ISSUE TITLE
calling makeAff callbacks more than once

### ISSUE THREAD

**Issue by hdgarrood** [slamdata/purescript-aff#31]
I wrote some (arguably broken) code that goes like this [here](https://github.com/hdgarrood/purescript-node-irc/blob/9519b34c42ddc8ed28344e46e464056c2ad04ee8/src/Node/IRC.purs#L82-L85):
```purescript
  waitForEvent client eventType =
    makeAff \_ success ->
      BareBones.addListener client eventType
        { fromArgumentsJS: const unit, action: success }
```

This is for an IRC client. I use this to make sure that the client doesn't attempt to send any messages until after it's connected to the server and joined a channel.

I call `waitForEvent client "join"`, and this adds an event listener which fires every time anyone joins the room, so `success` gets called more than once. This means that the rest of the `Aff` action gets executed multiple times.

Is it my responsibility to ensure that the `success` callback only gets called once, or do you think `Aff` should protect against this?

**Comment by garyb** [comment]
I'd think it's probably working as intended if we're saying `Aff` is `ErrorT (ContT Unit (Eff e) a` - there's nothing that says a continuation can only be resumed once.

**Comment by jdegoes** [comment]
Yeah, I personally do *not* prefer this type of usage because it leads to a very imperative style of coding, but there's no particular reason to disallow it (and, anyway, it's possible in `ContT`, `callCC`, etc.).
