### ISSUE TITLE
Add combinator to fork all of some `Foldable f => f (Aff eff a)`

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-aff#44]
In https://github.com/slamdata/purescript-halogen/pull/275 there's some code that uses `traverse_ forkAff` to run a bunch of `Aff`s in a fire-and-forget fashion. Since alot of these actions are likely going to be synchronous, this will blow the stack with enough handlers. I don't want to use `MonadRec` because it saves stack by using `later` (which can be bad in this case as it might cause UI flickering). I'd like an FFI combinator that defers stack behavior to an underlying `Foldable` instance, but is otherwise stack-safe.

```purescript
foreign import forkAndForget :: forall eff f a. Foldable f => f (Aff eff a) -> Aff eff Unit
```
```js
exports._forkAndForget = function(nonCanceler, foldl, f) {
  return function(success, error) {
    var voidF = function(){};

    foldl(function(acc) {
      return function(aff) {
        aff(voidF, voidF);
      };
    })({})(f);

    try {
      success({});
    } catch(e) {
      error(e);
    }

    return nonCanceler;
  };
}
```

Thoughts?

**Comment by garyb** [comment]
:+1: from me (we talked about it earlier on IRC)

@jdegoes?

**Comment by jdegoes** [comment]
Hou about instead, a `forkAll :: forall eff f a. (Foldable f) => f (Aff eff a) -> Aff eff Unit` with implementation given in PureScript using `forkAff`, `later`, `foldl`, etc?

**Comment by garyb** [comment]
I think that's the problem here, as I understand it, that the suggestion is trying to solve: there's not a good way to launch all these things at the moment without binds happening.

**Comment by garyb** [comment]
And the `later` issue will make the probably-synchronous initializers asynchronous in Halogen, which is what the mention of UI flickering was referring to.

**Comment by jdegoes** [comment]
Ah, I see. :+1: assuming there's no, e.g. tail recursive solution available to us. Also we should still call it `forkAll`.

**Comment by natefaubion** [comment]
I'm fine with `forkAll`. I mentioned `MonadRec` in the issue, and that will introduce `later` at some point, unfortunately. I think this is the only way to do it.

**Comment by paf31** [comment]
Something like `mapConcurrently :: List (Aff a) -> Aff (List a)` would be nice, using `Par` under the hood.

**Comment by jdegoes** [comment]
@paf31 Yeah, a parallel `sequence` would be cool (which you can probably get with `map unPar $ sequence (Par <$> affs)` or something).
