### ISSUE TITLE
Error from running the example in the slide.

### ISSUE THREAD

**Issue by wpoosanguansit** [slamdata/purescript-aff#54]
I am trying to use the library with use the library to work with GraphQL but I am not able to make everything work yet.  So I tried examples that I found in the slides to try things out.  With the simple example

```Purescript
main do
  a <- later           $ pure 42
  b <- later' 1000 $ pure 58
  return $ a + b  
```

I do get an error below:

* Build successful.
TypeError: error is not a function
    at /home/Projects/Purescript/purescript-express/examples/output/Control.Monad.Aff/foreign.js:177:7
    at Timeout._onTimeout (/home/Projects/Purescript/purescript-express/examples/output/Control.Monad.Aff/foreign.js:56:18)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

So here I am not sure if it is more of the set up on my machine that is causing the error.  Thanks for your help.

**Comment by garyb** [comment]
Where are the slides that you mentioned?

The problem here should be pretty easy to fix: you can't use an `Aff` value directly as a `main`, you need to `runAff` or `launchAff` it to turn it into an `Eff`:

``` purescript
main = launchAff do
  a <- later $ pure 42
  b <- later' 1000 $ pure 58
  return $ a + b 
```

This program won't do anything noticeable though, apart from waiting for 1 second before terminating. You'll probably want to log `a + b` to see the result.

**Comment by wpoosanguansit** [comment]
Thank you for your help.  I have got the example from:

https://github.com/degoes-consulting/lambdaconf-2015/blob/master/speakers/jdegoes/async-purescript/presentation.pdf <https://github.com/degoes-consulting/lambdaconf-2015/blob/master/speakers/jdegoes/async-purescript/presentation.pdf>

**Comment by wpoosanguansit** [comment]
Hi Gary,

I hope you do not mind I ask you here on how to use the library.   It would be great if there is an example of retrieving the value out of the Aff.  I am just not clear on how to take a value out of a function returned from makeAff :: Aff eff String.  I try to return pure value and runPure on it but it still has an error of Eff () String can not be matched.   Thanks for your help.

**Comment by garyb** [comment]
Perhaps this answer will help? http://stackoverflow.com/a/35439318/139614

Basically, when you're in `Aff`, you have to stay in `Aff` - similar to `Eff`, but moreso. You can use some horribly unsafe machinery to unwrap an `Eff` value, but that is not available when working with `Aff` values, as `Aff` is asynchronous, so internally uses something like callbacks to capture the results of evaluated values - there's not actually a value you can unwrap.

You can `launchAff` or `runAff` which will turn an `Aff` value into an `Eff` (which you can then use as the `main`), but doing so necessitates "throwing away" the result of the `Aff` for the reason mentioned above. So generally your entire `main` will be wrapped in `launchAff do ...`, as the `main` itself doesn't need to return a useful result.

**Comment by wpoosanguansit** [comment]
Thank you Gary.
