### ISSUE TITLE
Remove `MonadCont` instance

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-aff#59]
Since we don't want to encourage continuation-style behaviour for Aff

**Comment by garyb** [comment]
Doh, I thought we might have wanted to include this in 1.0.0...

**Comment by jdegoes** [comment]
I'd prefer to deprecate it for a number of releases. It's not really harming anything, AFAIK.

**Comment by garyb** [comment]
Oh ok, great! I had the impression that it might have been broken (slightly) by some of the recent changes.
