### ISSUE TITLE
`attempt` doesn't handle exceptions in Aff function

### ISSUE THREAD

**Issue by kika** [slamdata/purescript-aff#65]
It appears that `attempt` is supposed to handle exceptions in the Aff function it runs, but it doesn't despite having a `try ... catch...` block in its FFI implementation.
Repro case: 
1. Checkout https://github.com/Thimoteus/purescript-simple-request.git
2. Change `reddit.com` to `reddit.com:8088` at https://github.com/Thimoteus/purescript-simple-request/blob/master/test/Main.purs#L34
3. Run the test with `pulp test`

The program bails out with `EPROTO` exception (because there's nothing ready for SSL handshake at port 8088).

Expected result: `Left Error` from `attempt` with the corresponding exception.

**Comment by jdegoes** [comment]
The first place to look is [here](https://github.com/Thimoteus/purescript-simple-request/blob/master/src/Node/SimpleRequest.js#L5). Make sure any place which can cause an exception will call the `onErr` callback.

**Comment by kika** [comment]
@jdegoes Does this mean that functions in Aff indeed do not catch exceptions and we need to catch ourselves and call error callbacks?
In [Aff.js](https://github.com/slamdata/purescript-aff/blob/master/src/Control/Monad/Aff.js) `_attempt` does use `try...catch...`, `_runAff` doesn't, `_liftEff` does again. I can't understand the system and difference.

**Comment by jdegoes** [comment]
@kika If you create your own `Aff`, you need to make sure that you always use the error callback in the event of an error. I am not sure why `_attempt` uses try / catch, probably we can delete that. The point is that if you create your own native `Aff`s which are functioning correctly, then `attempt` will always "catch" the error (through the error callback). If that does not happen, then it's a bug in `Aff` and will be fixed right away (in this case, I am not sure, but the Javascript code does not look safe to me).

**Comment by natefaubion** [comment]
`Aff` now only uses `try/catch` in `liftEff` and `makeAff`. It's expected that anything else uses the error channels.
