### ISSUE TITLE
Monomorphic liftEff

### ISSUE THREAD

**Issue by texastoland** [slamdata/purescript-aff#67]
Suggested by @paf31 in purescript/purescript#2061. He mentioned it might become unnecessary with fundeps? Besides being needed in come cases it's a confusing error message. See https://github.com/texastoland/purescript-localstorage/blob/refactor/test/DOM/WebStorage/Var.purs#L51-L52.

**Comment by garyb** [comment]
Fundeps have landed (:tada:) so this should be much better now.
