### ISSUE TITLE
Two ways to write Aff in the FFI

### ISSUE THREAD

**Issue by Risto-Stevcev** [slamdata/purescript-aff#69]
I've noticed that there are two ways to write Aff in the FFI: `makeAff` and using success and error like in `Control/Monad/Aff.js`.

**Version 1**

Main.js
```javascript
var fs = require('fs');

exports._readFile = function(path) {
  return function(success, error) {
    fs.readFile(path, 'utf8', function(err, data) {
      if (err)
        error(err);
      else
        success(data);
    });
  }
}
```

Main.purs
```purescript
foreign import _readFile :: forall e. String -> Aff (| e) String

readFile :: forall e. String -> Aff (| e) String
readFile = _readFile

main = launchAff $ do
  contents' <- attempt $ readFile "bower.json"
  case contents' of
    Left err -> log (message err)
    Right contents -> log contents
```

**Version 2**

Main.js
```javascript
exports._readFile = function(path, error, success) {
  return function() {
    fs.readFile(path, 'utf8', function(err, data) {
      if (err)
        error(err)();
      else
        success(data)();
    });
  } 
}
```

Main.purs
```purescript
foreign import _readFile :: forall e. Fn3 String (Error -> Eff (| e) Unit) (String -> Eff (| e) Unit) (Eff (| e) Unit)

readFile :: forall e. String -> Aff (| e) String
readFile path = makeAff (\error success -> runFn3 _readFile path error success)

main = launchAff $ do
  contents' <- attempt $ readFile "bower.json"
  case contents' of
    Left err -> log (message err)
    Right contents -> log contents
```

Both seem to work, but I like version 1 better because it's more succinct. Is there a "correct" version or are both okay to use?

**Comment by garyb** [comment]
Version 1 is the preferred way if you're producing an `Aff` from the FFI. `makeAff` is intended for producing `Aff` values from PureScript code. (And yes, I realise `affjax` is guilty of doing it the "wrong" way :wink:)

**Comment by Risto-Stevcev** [comment]
Thanks for clearing that up! :relieved:

**Comment by maackle** [comment]
Two years later: Is the first example still correct? I'm having problems with it, and the documentation contradicts it. Also, the documentation I've found has not been helpful in explaining how to produce an FFI function that takes parameters and returns an `Aff`...

https://github.com/slamdata/purescript-aff/blob/master/src/Control/Monad/Aff/Compat.purs#L23
