### ISSUE TITLE
Effect rows tricky to use

### ISSUE THREAD

**Issue by paf31** [slamdata/purescript-aff#7]
I am running into infinite type errors when using `makeAff` and `runAff` in Halogen, and I need to use `unsafeInterleaveEff` to get around them.

After spending some time on it ages ago, I sadly came to the conclusion that the only good way to deal with async code in `Eff` is to stick an `Async` effect everywhere - in the setup function, _and_ in the callback. Anything else leads to either duplicate labels or infinite types.

Would you be averse to:

```purescript
newtype Aff e a = Aff ((Error -> EffA e Unit) -> (a -> EffA e Unit) -> EffA e Unit)

runAff :: forall e a. (Error -> EffA e Unit) -> (a -> EffA e Unit) -> Aff e a -> EffA e Unit
makeAff :: forall e a. ((Error -> EffA e Unit) -> (a -> EffA e Unit) -> EffA e Unit) -> Aff e a
```

**Comment by jdegoes** [comment]
I was just thinking about changing this the other day, but in the other direction, that is, to remove the `async :: Async` effect from the type signature, so `Aff` would become:

```
newtype Aff e a = Aff ((Error -> Eff e Unit) -> (a -> Eff e Unit) -> Eff e Unit)
```

My reasoning is that a pure computation can be synchronous or asynchronous, and it should be possible to express a pure `a` computation using `forall e. Aff e a`. 

Would that work?

By the way, I definitely don't see any infinite types anywhere -- do you think that could be a typechecker issue?
