### ISSUE TITLE
Fix bug in callback

### ISSUE THREAD

**Issue by jdegoes** [slamdata/purescript-aff#79]
[here](https://github.com/slamdata/purescript-aff/commit/5b5c04c1c3b9a3610e502d5a008c2bc88655dc0a#commitcomment-18819162)

**Comment by garyb** [comment]
I already "fixed" this (deleted it) in #74, since `Debug.Trace` exists now and can save the same purpose. We have jshint setup so that code like this in the JS would be an error now too.
