### ISSUE TITLE
Remove `later` in favor of `sleep`

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-aff#82]
The signature of `later` no longer serves any semantic purpose. I think we should remove it in favor of `sleep :: Int -> Aff eff Unit`.

**Comment by rightfold** [comment]
`Data.Time.Duration.Milliseconds`?

**Comment by nwolverson** [comment]
Is `sleep` the correct name? Not to say it's not, but it might suggest a synchronous sleep, another term that is used for an async wait is `delay`.
