### ISSUE TITLE
Change type of launchAff to avoid duplicate label errors

### ISSUE THREAD

**Issue by rightfold** [slamdata/purescript-aff#88]
The current type is:

```purescript
launchAff :: forall e a. Aff e a -> Eff (err :: EXCEPTION | e) (Canceler e)
```

This causes duplicate label issues when the `Aff` action already has the `err :: EXCEPTION` effect in its type.

This problem should be solved by using the following type:

```purescript
launchAff :: forall e a. Aff (err :: EXCEPTION | e) a -> Eff (err :: EXCEPTION | e) (Canceler e)
```

Most old code should keep working because adding an effect to an action type isn't a problem.

**Comment by garyb** [comment]
The reason this was changed in the first place is that it makes the type lie. Launching an aff will never raise an exception.

**Comment by natefaubion** [comment]
It's not a lie, `launchAff` always has the potential to raise an exception, but it might not necessarily raise an exception you can catch.

**Comment by garyb** [comment]
(See #32 / #33).

On the other hand, it is a pain to work with as long as duplicate rows are disallowed, so I don't like either option particularly right now.

**Comment by garyb** [comment]
Ah actually, this is a little different than the linked discussion, and I even suggested the above. In that case, 👍.

**Comment by natefaubion** [comment]
This is irrelevant now the row restriction has been lifted.
