### ISSUE TITLE
putVar should return Eff

### ISSUE THREAD

**Issue by beckyconning** [slamdata/purescript-aff#93]
putVar is sync. 

having it as Aff means people will need to runAff it which is ok...

except runAffing async Affs can cause unexpected behaviour, you have to be careful and there is no type level information about which Avars are okay to runAff wherever and which aren't.

therefore i think that whilst putVar is "non-blocking" it should return Eff.

**Comment by beckyconning** [comment]
this is related to the whole ASYNC row effect thing too i think.

also this would need the EXCEPTION effect? 

perhaps both should be provided.

**Comment by natefaubion** [comment]
I think the solution to this is may be provide ` purescript-queues` implementation based an `Eff`, and change `AVar` to be an `Aff` wrapper around that. I don't particularly care for the way we have `AVar` organized in this library, and the only reasonable thing to do would be to split it out into a package with an `Eff` implementation.
