### ISSUE TITLE
Is MonadPlus instance lawful?

### ISSUE THREAD

**Issue by rightfold** [slamdata/purescript-aff#95]
`let f = if _ then throwError e else pure unit`

Then `(pure true <|> pure false) >>= f` is not the same as `(pure true >>= f) <|> (pure false >>= f)`. Because in the first example, the exception thrown by `f` is not caught.

**Comment by natefaubion** [comment]
I don't think your example is great, because it's observable the same. The first exception is caught, but the second one throws, which is identical to an outside observer. But in general, distributivity doesn't really apply to effects.

```
(log "foo" <|> log "bar") >>= \_ -> log "baz"
(log "foo" >>= \_ -> log "baz") <|> (log "foo" >>= \_ -> log "baz")
```

Are observably different.

**Comment by natefaubion** [comment]
Actually I take that back, I'm getting this mixed up with ParAff. That above is lawful.

**Comment by natefaubion** [comment]
And again you are right in your original post 😆 Long day...

**Comment by natefaubion** [comment]
I'll remove this instance in my branch.

**Comment by natefaubion** [comment]
Does this mean that `Alternative` is also bad, since it relies on similar distributivity?

**Comment by safareli** [comment]
IO like structures can't be MonadPlus (https://github.com/slamdata/purescript-io/issues/3)
But I think it can be lawful MonadOr (https://github.com/purescript/purescript-control/issues/35)
